version: "3"
services:
  social-graph-service:
    image: yg397/social-network-microservices:latest
    hostname: social-graph-service
    #    ports:
    #      - 10000:9090
    depends_on:
      - jaeger
      - social-graph-mongodb
    restart: always
    entrypoint: SocialGraphService
    deploy:
      placement:
        constraints: [node.hostname == node0]

  social-graph-mongodb:
    image: mongo
    hostname: social-graph-mongodb
    # ports:
    #   - 27018:27017
    restart: always
    deploy:
      placement:
        constraints: [node.hostname == node0]

  social-graph-redis:
    image: redis
    hostname: social-graph-redis
    # ports:
    #   - 6380:6379
    restart: always
    deploy:
      placement:
        constraints: [node.hostname == node0]


  home-timeline-redis:
    image: redis
    hostname: home-timeline-redis
    # ports:
    #   - 6381:6379
    restart: always
    deploy:
      placement:
        constraints: [node.hostname == node0]

  home-timeline-redis:
    depends_on:
      - jaeger
    hostname: home-timeline-redis
    # ports:
    #   - 6381:6379
    image: redis
    deploy:
      placement:
        constraints: [node.hostname == node0]

  compose-post-service:
    image: yg397/social-network-microservices:latest
    hostname: compose-post-service
    #    ports:
    #      - 10001:9090
    restart: always
    depends_on:
      - jaeger
    entrypoint: ComposePostService
    volumes:
      - ./config:/social-network-microservices/config
    deploy:
      placement:
        constraints: [node.hostname == node0]

  post-storage-service:
    image: yg397/social-network-microservices:latest
    hostname: post-storage-service
    ports:
      - 10002:9090
    restart: always
    depends_on:
      - jaeger
      - post-storage-mongodb
    entrypoint: PostStorageService
    volumes:
      - ./config:/social-network-microservices/config
    deploy:
      placement:
        constraints: [node.hostname == node0]

  post-storage-memcached:
    image: memcached
    hostname: post-storage-memcached
    #    ports:
    #      - 11212:11211
    restart: always
    deploy:
      placement:
        constraints: [node.hostname == node0]

  post-storage-mongodb:
    image: mongo
    hostname: post-storage-mongodb
    #    ports:
    #      - 27019:27017
    restart: always
    deploy:
      placement:
        constraints: [node.hostname == node0]

  user-timeline-service:
    image: yg397/social-network-microservices:latest
    hostname: user-timeline-service
    #    ports:
    #      - 10003:9090
    restart: always
    depends_on:
      - jaeger
      - user-timeline-mongodb
    entrypoint: UserTimelineService
    volumes:
      - ./config:/social-network-microservices/config
    deploy:
      placement:
        constraints: [node.hostname == node1]

  user-timeline-redis:
    image: redis
    hostname: user-timeline-redis
    #    ports:
    #      - 6383:6379
    restart: always
    deploy:
      placement:
        constraints: [node.hostname == node0]

  user-timeline-mongodb:
    image: mongo
    hostname: user-timeline-mongodb
    #    ports:
    #      - 27020:27017
    restart: always
    deploy:
      placement:
        constraints: [node.hostname == node0]

  url-shorten-service:
    image: yg397/social-network-microservices:latest
    hostname: url-shorten-service
    #    ports:
    #      - 10004:9090
    restart: always
    entrypoint: UrlShortenService
    depends_on:
      - jaeger
      - url-shorten-mongodb
    volumes:
      - ./config:/social-network-microservices/config
    deploy:
      placement:
        constraints: [node.hostname == node0]

  url-shorten-memcached:
    image: memcached
    hostname: url-shorten-memcached
    #    ports:
    #      - 11213:11211
    restart: always
    deploy:
      placement:
        constraints: [node.hostname == node0]

  url-shorten-mongodb:
    image: mongo
    hostname: url-shorten-mongodb
    #    ports:
    #      - 27021:27017
    restart: always
    deploy:
      placement:
        constraints: [node.hostname == node0]

  user-service:
    image: yg397/social-network-microservices:latest
    hostname: user-service
    #    ports:
    #      - 10005:9090
    restart: always
    depends_on:
      - jaeger
      - user-mongodb
    entrypoint: UserService
    volumes:
      - ./config:/social-network-microservices/config
    deploy:
      placement:
        constraints: [node.hostname == node0]

  user-memcached:
    image: memcached
    hostname: user-memcached
    #    ports:
    #      - 11214:11211
    restart: always
    deploy:
      placement:
        constraints: [node.hostname == node0]

  user-mongodb:
    image: mongo
    hostname: user-mongodb
    #    ports:
    #      - 27023:27017
    restart: always
    deploy:
      placement:
        constraints: [node.hostname == node0]

  media-service:
    image: yg397/social-network-microservices:latest
    hostname: media-service
    #    ports:
    #      - 10006:9090
    depends_on:
      - jaeger
      - media-mongodb
    restart: always
    entrypoint: MediaService
    volumes:
      - ./config:/social-network-microservices/config
    deploy:
      placement:
        constraints: [node.hostname == node0]

  media-memcached:
    image: memcached
    hostname: media-memcached
    #    ports:
    #      - 11215:11211
    restart: always
    deploy:
      placement:
        constraints: [node.hostname == node0]

  media-mongodb:
    image: mongo
    hostname: media-mongodb
    #    ports:
    #      - 27024:27017
    restart: always
    deploy:
      placement:
        constraints: [node.hostname == node0]

  text-service:
    image: yg397/social-network-microservices:latest
    hostname: text-service
    #    ports:
    #      - 10007:9090
    restart: always
    depends_on:
      - jaeger
    entrypoint: TextService
    volumes:
      - ./config:/social-network-microservices/config
    deploy:
      placement:
        constraints: [node.hostname == node0]

  unique-id-service:
    image: yg397/social-network-microservices:latest
    hostname: unique-id-service
    #    ports:
    #      - 10008:9090
    restart: always
    depends_on:
      - jaeger
    entrypoint: UniqueIdService
    volumes:
      - ./config:/social-network-microservices/config
    deploy:
      placement:
        constraints: [node.hostname == node0]

  user-mention-service:
    image: yg397/social-network-microservices:latest
    hostname: user-mention-service
    #    ports:
    #      - 10009:9090
    depends_on:
      - jaeger
    restart: always
    entrypoint: UserMentionService
    volumes:
      - ./config:/social-network-microservices/config
    deploy:
      placement:
        constraints: [node.hostname == node0]

  home-timeline-service:
    image: yg397/social-network-microservices:latest
    #image: modified:0.1
    hostname: home-timeline-service
    #    ports:
    #      - 10010:9090
    depends_on:
      - jaeger
    restart: always
    entrypoint: HomeTimelineService
    volumes:
      - ./config:/social-network-microservices/config
    deploy:
      placement:
        constraints: [node.hostname == node0]

  nginx-thrift:
    image: yg397/openresty-thrift:xenial
    hostname: nginx-thrift
    ports:
      - 8080:8080
    depends_on:
      - jaeger
    restart: always
    volumes:
      - ./nginx-web-server/lua-scripts:/usr/local/openresty/nginx/lua-scripts
      - ./nginx-web-server/pages:/usr/local/openresty/nginx/pages
      - ./nginx-web-server/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./nginx-web-server/jaeger-config.json:/usr/local/openresty/nginx/jaeger-config.json
      - ./gen-lua:/gen-lua
    deploy:
      placement:
        constraints: [node.hostname == node0]

  media-frontend:
    image: yg397/media-frontend:xenial
    hostname: media-frontend
    ports:
      - 8081:8080
    restart: always
    depends_on:
      - jaeger
    volumes:
      - ./media-frontend/lua-scripts:/usr/local/openresty/nginx/lua-scripts
      - ./media-frontend/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
    deploy:
      placement:
        constraints: [node.hostname == node0]

  jaeger:
    image: jaegertracing/all-in-one:latest
    hostname: jaeger-agent
    ports:
      #      - 5775:5775/udp
      #      - 6831:6831/udp
      #      - 6832:6832/udp
      #      - 5778:5778
      - 16686:16686
    #      - 14268:14268
    #      - 9411:9411
    restart: always
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    deploy:
      placement:
        constraints: [node.hostname == node0]
